### ISSUE TITLE
circular_buffer.get_last_value bug

### ISSUE THREAD

**Issue by vstadnytskyi** [vstadnytskyi/circular_buffer_numpy#1]
```
>>> dev.circular_buffer.get_last_value()
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    dev.circular_buffer.get_last_value()
  File "Z:\circular_buffer_LL.py", line 114, in get_last_value
    return get_last_N(N = 1)
NameError: name 'get_last_N' is not defined
```

**Comment by vstadnytskyi** [comment]
fixed
